Brands/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from django.contrib.auth import views as auth_views
from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)


urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^api/', include(router.urls,)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
]

main/urls.py
from django.conf.urls import url



urlpatterns = [
]

projects/urls.py
# projects/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "projects"
urlpatterns = [
    url(r'^$', views.projects, name='home'),
    url(r'^projects/(?P<pk>[0-9a-f-]+)$', views.project, name='project_home'),
    url(r'^search/$', views.get_data, name='search'),
    url(r'^analysis/$', views.analyse, name='analysis'),
    url(r'^info/$', views.info, name='info'),
    url(r'^tasks/$', views.task_control, name='task_control'),
    url(r'^search/results/(?P<data_pk>[\w-]+)/$', views.show_results, name='search_results'),
    url(r'^analytics/words_(?P<dataset_pk>[\w-]+)/$$', views.analyze_data, name="analyze_words"),
    url(r'^api/projects/$', views.ProjectsCreateReadView.as_view(), name='projects_rest_api'),
    url(r'^api/projects/(?P<pk>[0-9a-f-]+)$', views.ProjectsReadUpdateDeleteView.as_view(), name='tournament_rest_api'),
    url(r'^temp/$', views.temp, name='temp')

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

projects/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

import uuid
from django.db import models
from django.urls import reverse 
from django_countries.fields import CountryField
from django.utils import timezone
# Create your models here.

class Project(models.Model):

    project_id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    name = models.CharField(max_length=200, unique=True)
    description = models.CharField(max_length=200, null=True, blank=True)
    start_date = models.DateField(null=True, blank=True)
    finish_date = models.DateField(null=True, blank=True)

    def __str__(self):
        return self.name

class Dataset(models.Model):

    project = models.ForeignKey(Project, on_delete="models.CASCADE")

    filename = models.CharField(max_length=50, null=True, blank=True)
    query = models.CharField(max_length=200, null=True, blank=True)
    number_of_messages = models.IntegerField(null=True, blank=True)
    saved = models.BooleanField(default=True)
    life = models.BooleanField(default=False)

    def __str__(self):

        return self.filename


class User(models.Model):
    user_id = models.BigIntegerField(primary_key=True)
    screen_name = models.CharField(max_length=200, default='username')
    name = models.CharField(max_length=200, null=True, blank=True, default = 'name')
    statuses_count = models.IntegerField()
    following = models.IntegerField()
    followers = models.IntegerField()
    likes = models.IntegerField()
    description = models.CharField(max_length=300, null=True, blank=True)


    def __str__(self):
        return self.screen_name + "|" + str(self.user_id)

class Twitter_data(models.Model):

    message = models.CharField(max_length=500)
    likes = models.IntegerField()
    retweets = models.IntegerField()
    replies = models.IntegerField()
    user = models.ForeignKey(User, null=True, blank=True, on_delete=models.CASCADE)
    
    dataset = models.ForeignKey(Dataset, null=True, blank=True, on_delete=models.CASCADE)

class Analisys_data(models.Model):
    project = models.ForeignKey(Project, on_delete="models.CASCADE")
    dataset = models.ForeignKey(Dataset, null=True, blank=True, on_delete=models.CASCADE)
    date = models.DateField(null=True, blank=True)
    json_result = models.CharField(max_length=200)

projects/forms.py
from django import forms
from django.db.models import Q
from .models import Project, User, Twitter_data, Dataset



class NewProjectForm(forms.ModelForm):

    class Meta:
        model = Project
        fields = ['name', 'description', 'start_date']
        widgets = {
            'start_date': forms.DateTimeInput(attrs={'class': 'datetime-input'})
        }

class GetDataForm(forms.Form):

    project = forms.ChoiceField(choices = [])
    query = forms.CharField(label='Search query', max_length=100)
    number = forms.IntegerField(max_value=1000000)
    result_choices = (('recent', 'Recent'),('mixed','Mixed'), ('popular', 'Popular'))
    result_type = forms.ChoiceField(choices=result_choices)

    def __init__(self, *args, **kwargs):
        super(GetDataForm, self).__init__(*args, **kwargs)
        self.fields['project'].choices = [(x.pk, x.name) for x in Project.objects.all()]

projects/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals
from operator import itemgetter
from datetime import datetime
import time
import kombu.five
import os 

from django.shortcuts import render
from .models import Project, User, Twitter_data,  Dataset
from .forms import *
from .serializers import ProjectSerializer

from rest_framework.generics import ListCreateAPIView, RetrieveUpdateDestroyAPIView 

from django.shortcuts import render, get_object_or_404, redirect
from django.http import HttpResponse
from django.utils import timezone
from django.contrib.auth.decorators import login_required
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
from django.db.models import Q
from django.contrib import messages
from django.views import View


from .data import *
from .tasks import temp_task, stream_task, premium_task
from celery.task.control import inspect, revoke

from .analytics import wordFreq




# Create your views here.
def index(request):
    """
    Home page
    """


    return render(request, 'projects/index.html')

def info(request):
    """
    Info page
    """



    return render(request, 'projects/info.html')

def projects(request):

    projects = Project.objects.all()

    if request.method == "POST":
        form = NewProjectForm(request.POST)
        if form.is_valid():
            project = form.save()
            project.save()
            if 'create' in request.POST:
                messages.info(request, 'Project created.')
                return redirect('projects:home')
    else:
        form = NewProjectForm()

    return render(request, 'projects/projects.html', {'form': form, 'projects': projects})

def project(request, pk):

    project = Project.objects.get(pk=pk)

    datasets = Dataset.objects.filter(project=project).order_by('-pk')

    return render(request, 'projects/project.html', {'project': project, 'datasets': datasets})

def show_results(request, data_pk):
    data = Dataset.objects.get(pk=data_pk)
    project = data.project
    texts = []
    
    try:
        cwd = os.getcwd()
        dataj = json.load(open(cwd + '/projects/twitter/static/{0}.json'.format(data.filename), 'r'))
        statuses = dataj['statuses']

        for s in statuses:
            dset = [s['text'],s['favorite_count'], s['user']['screen_name'], s['created_at'], s['text'].split('://')[-1]]
            texts.append(dset)
        
        texts = sorted(texts, key=itemgetter(1), reverse=True)
    except Exception as e:
        print(e)
        json.loads(request.POST.get('DATA_NOT_RECIEVED_YETs', '{}'))



    return render(request, 'projects/results.html',{'texts': texts, 'project': project, 'dataset': data})

def get_data(request):
    if request.method == 'POST': # If the form has been submitted...
        form = GetDataForm(request.POST) # A form bound to the POST data
        if form.is_valid():
            project = Project.objects.filter(pk=form.cleaned_data['project'])
            filename = form.cleaned_data['query'] + "_" + datetime.now().strftime("%d%m%Y_%H%M")
            result_type = form.cleaned_data['result_type']

            if form.cleaned_data['number'] > 0:
                number = form.cleaned_data['number']
            else:
                number = 150

            cwd = os.getcwd()
            created_file = open(cwd + '/projects/twitter/static/{0}.json'.format(filename), 'w+')
            ds = Dataset.objects.create(project=project[0], filename=filename, query=form.cleaned_data['query'])
            
            
            query = form.cleaned_data['query']
            print(form.cleaned_data['query'])
            if 'get_rest' in request.POST:
                temp_task.delay(query, number, filename, result_type)
                time.sleep(10)
                
            elif 'get_stream' in request.POST:
                stream_task.delay(query, number, filename, result_type)
            elif 'get_full' in request.POST:
                premium_task.delay(query, number, filename, result_type)
                if int(form.cleaned_data['number']) > 500:
                    time.sleep(10)
                elif int(form.cleaned_data['number']) > 5000:
                    time.sleep(15)
                else:
                    time.sleep(3)
            #twitter_stream(query, 5, 10)
        return redirect('projects:search_results', data_pk=ds.pk) # Redirect after POST
            

    else:
        form = GetDataForm() # An unbound form

    return render(request, 'projects/get_data.html', {
        'form': form,
    })

def analyze_data(request, dataset_pk):

    wordFreq(dataset_pk)
    cwd = os.getcwd()
    jdata = json.load(open(cwd + "/projects/twitter/static/analysis_data.json",'r'))

    max_data = 0

    for it in jdata:
        if jdata[it] > max_data:
            max_data = jdata[it]

    return render(request, 'projects/chart_words.html', {'jdata': jdata, 'max_data': max_data })

def task_control(request):

    i = inspect()
    # Show the items that have an ETA or are scheduled for later processing
    scheduled = i.scheduled()

    scheduled = next (iter (scheduled.values()))
    # Show tasks that are currently active.
    active = i.active()
    active = next (iter (active.values()))

    for t in active:
        time_start = t['time_start']        
        t['time_start'] = datetime.fromtimestamp(time.time() - (kombu.five.monotonic() - time_start))

    # Show tasks that have been claimed by workers
    reserved = i.reserved()

    task_id = 0
    for i, e in request.POST.items():        
        if 'stop' in i:
            print(i, e)
            task_id = i

    if task_id in request.POST:
        task_id = task_id.split('stop')[-1]       
        print("Clossing task {0}".format(task_id))
        revoke(task_id, terminate=True)
        messages.info(request, 'Task stopped.')
        time.sleep(5)
        return render(request, 'projects/tasks.html', {
                    'scheduled': scheduled,
                    'active': active, 
                    'reserved': reserved})

    return render(request, 'projects/tasks.html', {
        'scheduled': scheduled,
        'active': active, 
        'reserved': reserved})

def analyse(request):

    return render(request, 'projects/analysis.html')

def temp(request):

    return render(request, 'projects/temp.html')


""" API VIEWS BELOW """

class ProjectsCreateReadView(ListCreateAPIView):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer
    lookup_field = 'name'

class ProjectsReadUpdateDeleteView(RetrieveUpdateDestroyAPIView):
    queryset = Project.objects.all()
    serializer_class = ProjectSerializer
    lookup_field = 'pk'

projects/templates/projects/analysis.html
{% extends 'projects/base.html' %}

{% block content %}
<style>
        * {
            box-sizing: border-box;
        }
        
        /* Create two equal columns that floats next to each other */
        .column {
            float: left;
            width: 50%;
            padding: 10px;
            height: 300px; /* Should be removed. Only for demonstration */
        }
        
        /* Clear floats after the columns */
        .row:after {
            content: "";
            display: table;
            clear: both;
        }
        </style>
<h1>Інтелектуальний аналіз даних бренду</h1>
<div class="row">
        <div class="column">
            <h3>Кластерний аналіз</h3>
        </div>
        <div class="column">
            <h3>Аналіз даних в нейронній мережі</h3>
        </div>
      </div>

{% endblock %}

projects/templates/projects/base.html
{% load static %}
<!doctype html>
<html>
    <head>
        <title>Brands</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">      
        <link rel="shortcut icon" type="image/png" href="{% static '/favicon.ico'%}"/>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->     
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://use.fontawesome.com/ad4f6e3394.js"></script>
        <!-- Fonts -->
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link href="//fonts.googleapis.com/css?family=Abril+Fatface&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link href="//fonts.googleapis.com/css?family=Merriweather&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <!-- Losal stylesheets -->
        <link rel="stylesheet" type="text/css" href="{% static 'projects/css/base.css' %}">
    </head>
<body>
    <div>
    <nav class="navbar navbar-expand-md navbar-light bg-faded">
            <button class="navbar-toggler navbar-toggler-right" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
                <span class="navbar-toggler-icon"></span>
            </button>
            <a class="navbar-brand" href="#">Brands Managements</a>
            
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'projects:home' %}">Додому <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'projects:search' %}">Отримат дані</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'admin:index' %}">Сторінка адміністратора</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'projects:analysis' %}">Аналіз даних</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'projects:task_control' %}">Поточні задачі</a>
                    </li>
                    <li class="nav-item">
                            <a class="nav-link" href="{% url 'projects:info' %}">About</a>
                        </li>
                    <li class="nav-item">
                        <a class="nav-link disabled" href="#">Disabled</a>
                    </li>
                    <li class="nav-item">
                        <a href="#" class="nav-link"><span class="glyphicon glyphicon-user"></span> Sign Up</a></li>
                        <li class="nav-item">
                                {% if user.is_authenticated %}
                                    {{ user.username }}|
                                    <a href="{% url 'logout' %}" class="nav-link">logout</a>
                                {% else %}
                                    <a href="{% url 'login' %}" class="nav-link"><span class="glyphicon glyphicon-log-in"></span> Login</a>
                                {% endif %}
                        </li>
                </ul>
                <form class="form-inline my-2 my-lg-0">
                <input class="form-control mr-sm-2" type="text" placeholder="Пошук">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Пошук</button>
                </form>
            </div>
    </nav>
    </div>

    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{ message }}
                </div>
        {% endfor %}
        </ul>
    {% endif %}
 
    <div class="content container">
            {% block content %}
            {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
</html>

projects/templates/projects/chart_words.html
<!DOCTYPE html>
<meta charset="utf-8">
<head>
    <title>
        Research page
    </title>
</head>
<style>
 body {
     background-color: lightblue;
 }
 svg {
    display: block;
    margin: auto;
     background-color: white;
 }
 H1{
     text-align: center;
 }
</style>

<script src="https://d3js.org/d3.v4.min.js"></script>

<body>
    <H1>Statistical word analysis</H1>
    <svg class="chart"></svg>
</body>

<script>
var data = [
{% for k, i in jdata.items %}
    {"name":"{{k}}",
    "value" :{{i}}},
{% endfor %}
    ];
var color = d3.scaleOrdinal(d3.schemeCategory20c);
var max_x = {{max_data}};
var margin = {top: 20, right: 30, bottom: 30, left: 40},
    width = 960 - margin.left - margin.right,
    height = 500 - margin.top - margin.bottom;
var x = d3.scaleBand()
    .range([0, width])
    .paddingInner(0.05);
var y = d3.scaleLinear()
    .domain([0, max_x])
    .range([height, 0]);
x.domain(data.map(function(d) { return d.name; }));
y.domain([0, d3.max(data, function(d) { return d.value; })]);
var xAxis = d3.axisBottom(x)
    .ticks(data.size);
var yAxis = d3.axisLeft(y)
    .ticks(10);
var chart = d3.select(".chart")
    .attr("width", width + margin.left + margin.right)
    .attr("height", height + margin.top + margin.bottom)
  .append("g")
    .attr("transform", "translate(" + margin.left + "," + margin.top + ")");
  chart.append("g")
      .attr("class", "x axis")
      .attr("transform", "translate(0," + height + ")")
      .call(xAxis);
  chart.append("g")
      .attr("class", "y axis")
      .call(yAxis);
  var bars = chart.selectAll(".bar")
      .data(data)
    .enter().append("rect")
      .attr("class", "bar")
      .attr("id", function(d, i) {
            return i;
        })
      .attr("x", function(d) { return x(d.name); })
      .attr("y", function(d) { return y(d.value); })
      .attr("height", function(d) { return height - y(d.value); })
      .attr("width", x.bandwidth())
      .on('mouseover', function() {
            d3.select(this)
            	.attr("fill", "LightCoral");
        })
        .on("mouseout", function(d, i) {
            d3.select(this).attr("fill", function() {
                return "" + color(this.id) + "";
            });
        });
      d3.selectAll('rect').attr("fill", function(d, i) {
            return color(i);});
function type(d) {
  d.value = +d.value; // coerce to number
  return d;
}
</script>

projects/templates/projects/get_data.html
{% extends 'projects/base.html' %}

{% block content %}
<div class="form">
    <h1>Введіть параметри пошуку:</h1>
    <form method="POST">{% csrf_token %}
        {{ form.as_p }}
        
        <button type="submit" class="save btn btn-default" name='get_rest'>Search</button>
        <button type="submit" class="save btn btn-default" name='get_stream'>Get live data</button>   
        <button type="submit" class="save btn btn-default" name='get_full'>TEST</button>   

    </form>
</div>
<script>
        $(function () {
            $('.datetime-input').datetimepicker({
                format:'YYYY-MM-DD HH:mm:ss'
            });
        });
    </script>
{% endblock %}

projects/templates/projects/index.html
<h1>Hello!</h1>

projects/templates/projects/info.html
{% extends 'projects/base.html' %}

{% block content %}
<h2>About</h2>
<p>This web-app dedicated to monitoring specific topics regarding brands on different social media platforms.</p>
{% endblock %}

projects/templates/projects/project.html
{% extends 'projects/base.html' %}

{% block content %}
<style> 
.datasets {
    -webkit-column-count: 2; /* Chrome, Safari, Opera */
    -moz-column-count: 2; /* Firefox */
    column-count: 2;
}
</style>

<h2>{{ project.name }}</h2>
<h3>Опис: </h3>
<p>{{ project.description }}</p>
<a href="{% url 'projects:search' %}"><button type="button" class="btn btn-outline-info">Додати даних</button></a>
<hr>

<p><span style="width:10px; display:inline-block; height:10px; background-color:#45f442; border-radius:3px; padding:3px"></span> - дані збираються в "прямому ефірі"</p>
<h3>Датасети проекту:</h3>

<div class="datasets">
{% for dataset in datasets %}
    <p><a style="{% if dataset.life == True %}background-color:#45f442{% endif %}; border-radius:3px; padding:3px" href="{% url 'projects:search_results' data_pk=dataset.pk %}">{{ dataset.filename }}</a><br>
        Кількість повідомлень: {{ dataset.number_of_messages }}<br>
        <a href="{% url 'projects:analyze_words' dataset_pk=dataset.pk %}"><button type="button" class="btn btn-primary">Аналіз</button></a>

    </p>
{% endfor %}
</div>

<style>
    
</style>
{% endblock %}

projects/templates/projects/projects.html
{% extends 'projects/base.html' %}

{% block content %}


<div class="projects">
    <h2>Оберіть проект:</h2>
{% for project in projects %}

    <a href="{% url 'projects:project_home' pk=project.pk %}"><h2>{{ project.name }}</h2></a>
{% endfor %}
</div>
<hr>
<div class="form">
    <h1>Створити новий проект</h1>
    <form method="POST" class="tournament-form">{% csrf_token %}
        {{ form.as_p }}
        
        <button type="submit" class="save btn btn-default" name='create'>Створити</button>

    </form>
</div>
<script>
        $(function () {
            $('.datetime-input').datetimepicker({
                format:'YYYY-MM-DD HH:mm:ss'
            });
        });
    </script>
{% endblock %}

projects/templates/projects/results.html
{% extends 'projects/base.html' %}

{% block content %}
<div>
<a href="{% url 'projects:project_home' pk=project.pk %}"><button type="button" class="btn btn-outline-info">Back to project</button></a>
</div>
<div>
<h3>Search results for <b>{{ dataset.query }}</b>. Found {{ dataset.number_of_messages }} messages.</h3>
{% for t in texts %}
    <h4>{{ t.3 }} | @{{ t.2 }}: </h4>
    <a href="https://{{ t.4 }}"><p>{{ t.0 }} | {{ t.1 }}  &#9829;</p></a>

{% endfor %}
</div>
<script type="text/javascript">
    setInterval(function() {
                  window.location.reload();
                }, 60000); 
</script>
{% endblock %}

projects/templates/projects/tasks.html
{% extends 'projects/base.html' %}

{% block content %}

<h2>Task monitoring center</h2>
<h3>Tasks</h3>
<h4>Active:</h4>
<p>
    {% for task in active %}
        Hostname: {{ task.hostname }}<br>
        Time started: {{ task.time_start }}<br>
        Arguments: {{ task.args }}<br>
        Priority: {{ task.delivery_info.priority }}<br>
        <form method="POST">{% csrf_token %}            
            <button type="submit" class="save btn btn-danger" name="stop{{ task.id }}">Stop</button>
        </form>
    {% endfor %}
</p>
<h4>Scheduled:</h4>
<p>
{% for task in scheduled %}
    Hostname: {{ task.hostname }}<br>
    Time started: {{ task.time_start }}<br>
    Arguments: {{ task.args }}<br>
    Priority: {{ task.delivery_info.priority }}<br>
{% endfor %}
</p>
<h4>Reserved:</h4>
<p>
    {% for task in reserved %}
        Hostname: {{ task.hostname }}<br>
        Time started: {{ task.time_start }}<br>
        Arguments: {{ task.args }}<br>
        Priority: {{ task.delivery_info.priority }}<br>
    {% endfor %}
</p>

{% endblock %}

projects/templates/projects/temp.html
<!DOCTYPE html>
<html>
<head>
<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
<script> 
$(document).ready(function(){
    $("#flip").click(function(){
        $("#panel").slideDown("slow");
    });
});
</script>
 
<style> 
#panel, #flip {
    padding: 5px;
    text-align: center;
    background-color: #e5eecc;
    border: solid 1px #c3c3c3;
}

#panel {
    padding: 50px;
    display: none;
}
</style>
</head>
<body>
 
<div id="flip">Click to slide down panel</div>
<div id="panel">Hello world!</div>

</body>
</html>