Brands/urls.py
from django.conf.urls import include, url
from django.contrib import admin
from django.contrib.auth import views
from django.conf import settings
from django.conf.urls.static import static
from rest_framework import routers
from django.contrib.auth import views as auth_views
from . import views

router = routers.DefaultRouter()
router.register(r'users', views.UserViewSet)
router.register(r'groups', views.GroupViewSet)


urlpatterns = [

    url(r'^$', views.index, name='index'),
    url(r'^admin/', admin.site.urls),
    url(r'^projects/', include('projects.urls', namespace='projects')),
    url(r'^api/', include(router.urls,)),
    url(r'^api-auth/', include('rest_framework.urls', namespace='rest_framework')),
    url(r'^login/$', auth_views.login, name='login'),
    url(r'^logout/$', auth_views.logout, name='logout'),
]

main/urls.py
from django.conf.urls import url



urlpatterns = [
]

projects/urls.py
# projects/urls.py
from django.conf.urls import url
from . import views
from django.conf import settings
from django.conf.urls.static import static

app_name = "projects"
urlpatterns = [
    url(r'^$', views.projects, name='home'),
    url(r'^projects/(?P<pk>[0-9a-f-]+)$', views.project, name='project_home'),
    url(r'^search/$', views.get_data, name='search'),
    url(r'^analysis/$', views.analyse, name='analysis'),
    url(r'^info/$', views.info, name='info'),
    url(r'^tasks/$', views.task_control, name='task_control'),
    url(r'^search/results/(?P<data_pk>[\w-]+)/$', views.show_results, name='search_results'),
    url(r'^analytics/words_(?P<dataset_pk>[\w-]+)/$$', views.analyze_data, name="analyze_words"),
    url(r'^api/projects/$', views.ProjectsCreateReadView.as_view(), name='projects_rest_api'),
    url(r'^api/projects/(?P<pk>[0-9a-f-]+)$', views.ProjectsReadUpdateDeleteView.as_view(), name='tournament_rest_api'),
    url(r'^temp/$', views.temp, name='temp')

] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

main/views.py
from django.shortcuts import render

main/templates/base.html
{% load staticfiles %}
<!doctype html>
<html>
    <head>
        <title>Brands</title>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">      
        <link rel="shortcut icon" type="image/png" href="{% static '/favicon.ico'%}"/>
        <!-- Bootstrap CSS -->
        <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
        <!-- Optional JavaScript -->
        <!-- jQuery first, then Popper.js, then Bootstrap JS -->     
        <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
        <script src="https://use.fontawesome.com/ad4f6e3394.js"></script>
        <!-- Fonts -->
        <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link href="//fonts.googleapis.com/css?family=Abril+Fatface&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <link href="//fonts.googleapis.com/css?family=Merriweather&subset=latin,latin-ext" rel="stylesheet" type="text/css">
        <!-- Losal stylesheets -->
    </head>
<body>
    {% if messages %}
        <ul class="messages">
        {% for message in messages %}
            <div class="alert alert-warning alert-dismissible" role="alert">
                <button type="button" class="close" data-dismiss="alert" aria-label="Close"><span aria-hidden="true">&times;</span></button>
                {{ message }}
                </div>
        {% endfor %}
        </ul>
    {% endif %}
 
    <div class="content container">
            {% block content %}
            {% endblock %}
    </div>

    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.3/umd/popper.min.js" integrity="sha384-vFJXuSJphROIrBnz7yo7oB41mKfc8JzQZiCq4NCceLEaO4IHwicKwpJf9c9IpFgh" crossorigin="anonymous"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.2/js/bootstrap.min.js" integrity="sha384-alpBpkh1PFOepccYVYDB4do5UnbKysX5WZXm3XxPqe5iKTfUKjNkCk9SaVuEZflJ" crossorigin="anonymous"></script>
</body>
</html>

main/templates/index.html
<!doctype html>

<html lang="en">
<head>
  <meta charset="utf-8">

  <title>Home</title>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">      
  <!-- Bootstrap CSS -->
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-beta.3/css/bootstrap.min.css" integrity="sha384-Zug+QiDoJOrZ5t4lssLdxGhVrurbmBWopoEl+M6BdEfwnCJZtKxi1KgxUyJq13dy" crossorigin="anonymous">
  <!-- Optional JavaScript -->
  <!-- jQuery first, then Popper.js, then Bootstrap JS -->     
  <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.3.1/jquery.min.js"></script>
  <script src="https://use.fontawesome.com/ad4f6e3394.js"></script>
  <!-- Fonts -->
  <link href="//fonts.googleapis.com/css?family=Lobster&subset=latin,latin-ext" rel="stylesheet" type="text/css">
  <link href="//fonts.googleapis.com/css?family=Abril+Fatface&subset=latin,latin-ext" rel="stylesheet" type="text/css">
  <link href="//fonts.googleapis.com/css?family=Merriweather&subset=latin,latin-ext" rel="stylesheet" type="text/css">
  <!-- Losal stylesheets -->
</head>
</head>

<body>
    <div class="container">
    <h1>Hello, World</h1>
    <h2>Brands here</h2>
    <a href="{% url 'projects:home' %}"><button type="button" class="btn btn-secondary btn-lg">PROJECTS HOME</button></a>
    </div>
</body>
</html>